[pytest]
<<<<<<< HEAD
pythonpath = .
testpaths = tests
=======
testpaths = tests
pythonpath = .
<<<<<<< HEAD
python_files = test_*.py
>>>>>>> a082d70d702a3bf8f095d3a7c7862a776493b298
=======
>>>>>>> day-09
