[pytest]
testpaths = task-5/tests
pythonpath = .
python_files = test_*.py
python_classes = Test*
python_functions = test_*
[pytest]
filterwarnings =
    ignore:'asyncio.iscoroutinefunction' is deprecated:DeprecationWarning
