[pytest]

pythonpath =
    day17
    day18

testpaths =
    day17/tests
    day18/tests

norecursedirs =
    __pycache__
    .pytest_cache

filterwarnings =
    ignore:The anyio\.abc\.BlockingPortal alias is deprecated:DeprecationWarning:starlette\.testclient